# -*- coding: utf-8 -*-
"""classes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19-U6FwgLhptaGkXZKbitvZOLOB68emDQ
"""

import time
import random
import thread



class Station(object):
  
  #def __init__(self):
      #self.type_id = type_id
      #self.id = id
      #self.name = name
      
  cnt1 = 0
  cnt2 = 0     
  
  def Init_station(self):
  
    print("Hello")
    global cnt1
    cnt1 = cnt1+1
    
    
  def Execute_routine(self,routine_id):
    global cnt2
    cnt2 = cnt2+1
    
    #while(1):
      #menu = raw_input ("Hello, please choose form following routine IDs (1,2,3) and press enter:\n"
      #"1\n"
      #"2\n"
      #"3\n")
    
    if(routine_id<1 or routine_id>3):
      print("routine_id out of bound. Insert integral values 1,2 or 3 only")
    
    if(routine_id == 1):
      print("1")
      time.sleep(5)

      
    if(routine_id == 2):
      print("2")
      time.sleep(5)

      
    if(routine_id == 3):
      print("3")
      time.sleep(5)

    if(cnt2 > cnt1):
      print("Station not initialized")
    
    
  def Shutdown_station(self): 
    print("bye")
    
    global cnt1
    cnt1=0
    
    global cnt2
    cnt2=0
    
    
if __name__ == '__main__':
   
  c = Station()
  
  #c.Init_station()
  c.Execute_routine(4)
  #c.Init_station()
  c.Shutdown_station()
  c.Init_station()
